/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as ConsensusRouteImport } from './routes/consensus'
import { Route as DetectRouteImport } from './routes/detect'
import { Route as ExplainRouteImport } from './routes/explain'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as ModelsModelIdRouteImport } from './routes/models.$modelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsensusRoute = ConsensusRouteImport.update({
  id: '/consensus',
  path: '/consensus',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectRoute = DetectRouteImport.update({
  id: '/detect',
  path: '/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainRoute = ExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/consensus': typeof ConsensusRoute
  '/detect': typeof DetectRoute
  '/explain': typeof ExplainRoute
  '/monitor': typeof MonitorRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/': typeof ModelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/consensus': typeof ConsensusRoute
  '/detect': typeof DetectRoute
  '/explain': typeof ExplainRoute
  '/monitor': typeof MonitorRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models': typeof ModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/consensus': typeof ConsensusRoute
  '/detect': typeof DetectRoute
  '/explain': typeof ExplainRoute
  '/monitor': typeof MonitorRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/': typeof ModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batch'
    | '/consensus'
    | '/detect'
    | '/explain'
    | '/monitor'
    | '/models/$modelId'
    | '/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batch'
    | '/consensus'
    | '/detect'
    | '/explain'
    | '/monitor'
    | '/models/$modelId'
    | '/models'
  id:
    | '__root__'
    | '/'
    | '/batch'
    | '/consensus'
    | '/detect'
    | '/explain'
    | '/monitor'
    | '/models/$modelId'
    | '/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchRoute: typeof BatchRoute
  ConsensusRoute: typeof ConsensusRoute
  DetectRoute: typeof DetectRoute
  ExplainRoute: typeof ExplainRoute
  MonitorRoute: typeof MonitorRoute
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consensus': {
      id: '/consensus'
      path: '/consensus'
      fullPath: '/consensus'
      preLoaderRoute: typeof ConsensusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detect': {
      id: '/detect'
      path: '/detect'
      fullPath: '/detect'
      preLoaderRoute: typeof DetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain': {
      id: '/explain'
      path: '/explain'
      fullPath: '/explain'
      preLoaderRoute: typeof ExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchRoute: BatchRoute,
  ConsensusRoute: ConsensusRoute,
  DetectRoute: DetectRoute,
  ExplainRoute: ExplainRoute,
  MonitorRoute: MonitorRoute,
  ModelsModelIdRoute: ModelsModelIdRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
